# Generated by Django 4.1.7 on 2023-03-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gifs',
        ),
        migrations.AddField(
            model_name='gif',
            name='Category',
            field=models.ManyToManyField(related_name='gifs', to='gifs.category'),
        ),
        migrations.AlterField(
            model_name='gif',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
