# Generated by Django 4.1.7 on 2023-03-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='NoImageAvailable.jpg', upload_to=''),
        ),
    ]
