# Generated by Django 4.1.7 on 2023-03-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
