# Generated by Django 4.1.7 on 2023-03-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_numbers_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
