# Generated by Django 4.1.7 on 2023-03-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='realtors/')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_MVP', models.BooleanField(default=False)),
                ('hire_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
