# Generated by Django 4.1.7 on 2023-03-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rentalrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='real_cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
