# Generated by Django 4.1.7 on 2023-03-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_vehicle_real_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Cruiser', 'Cruiser'), ('Touring', 'Touring'), ('Sports', 'Sports'), ('Off-Road', 'Off-Road'), ('Dual-Purpose', 'Dual-Purpose')], max_length=20),
        ),
    ]
