# Generated by Django 4.1.7 on 2023-03-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
