# Generated by Django 4.1.7 on 2023-03-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Musicals', 'Musicals'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Science-Fiction', 'Science-Fiction'), ('Sports', 'Sports'), ('Thriller', 'Thriller'), ('Western', 'Western')], max_length=20, null=True),
        ),
    ]
