# Generated by Django 4.1.7 on 2023-03-17 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posters/')),
                ('explanation_img', models.CharField(max_length=100)),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
    ]
